project:
  output-dir: ./reports

lang: fr

format:

  html:
    toc: true
    toc-title: Sommaire
    toc-depth: 4
    number-sections: true
    number-depth: 2
    mermaid: 
      theme: forest

  pdf:
    toc: true
    toc-title: Sommaire
    toc-depth: 4
    number-sections: true
    number-depth: 2
    highlight-style: tango
    mermaid:
      theme: forest
  